{
    "swagger": "2.0",
    "info": {
        "description": "Bitex application programming interface (API) allows our clients to access and control their accounts, using custom written software. <br/> With the inclusion of the new BTC/AED currency pair, we've added new endpoints for some API calls (info about specific calls below). The old endpoints are still available and have not changed. We strongly suggest however, that you refer to the API for future references.",
        "version": "1.0.0",
        "title": "Bitex",
        "termsOfService": "http://bitex.com",
        "contact": {
        "email": "admin@bitex.com"
    },
    "license": {
        "name": "Bitex API",
        "url": "http://bitex.com"
    }
    },
    "host": "api.bitex.com",
    "basePath": "/api",
    "tags": [
        {
            "name": "User",
            "description": "Everything about trading"
        },
        {
            "name": "Assets",
            "description": "Everything about trading"
        },
        {
            "name": "Balance",
            "description": "Everything about trading"
        },
        {
            "name": "Trading",
            "description": "Everything about trading"
        },
        {
            "name": "Market",
            "description": "Everything about market trading"
        }
    ],
    "schemes": [
        "http",
        "https"
    ],
    "paths": {
        "/auth/login": {
            "post": {
                "tags": [
                    "User"
                ],
                "summary": "User login.",
                "description": "User login",
                "operationId": "user.login",
                "security": [
                    {
                        "petstore_auth": [
                            "user.login"
                        ]
                    }
                ]
            }
        },
        "/auth/register": {
            "get": {
                "tags": [
                    "User"
                ],
                "summary": "Register user.",
                "description": "Register user.",
                "operationId": "user.register",
                "security": [
                    {
                        "petstore_auth": [
                            "user.register"
                        ]
                    }
                ]
            }
        },
        "/trading/asset/lists": {
            "post": {
                "tags": [
                    "Assets"
                ],
                "summary": "Get assets lists.",
                "description": "Get assets lists",
                "operationId": "asset.list",
                "security": [
                    {
                        "petstore_auth": [
                            "asset.list"
                        ]
                    }
                ]
            }
        },
        "/trading/order/depth": {
            "post": {
                "tags": [
                    "Trading"
                ],
                "summary": "Order depth.",
                "description": "",
                "operationId": "order.depth",
                "security": [
                    {
                        "petstore_auth": [
                            "read:order"
                        ]
                    }
                ]
            }
        },
        "/trading/order/limit": {
            "post": {
                "tags": [
                    "Trading"
                ],
                "summary": "Place limit order.",
                "description": "Place limit order",
                "operationId": "order.put_limit",
                "security": [
                    {
                        "petstore_auth": [
                            "create:order"
                        ]
                    }
                ]
            }
        },
        "/trading/order/market": {
            "post": {
                "tags": [
                    "Trading"
                ],
                "summary": "Place maket order.",
                "description": "Place market order",
                "operationId": "order.put_market",
                "security": [
                    {
                        "petstore_auth": [
                            "create:order"
                        ]
                    }
                ]
            }
        },
        "/trading/order/cancel": {
            "post": {
                "tags": [
                    "Trading"
                ],
                "summary": "Cancel order.",
                "description": "Cancel order",
                "operationId": "order.cancel",
                "security": [
                    {
                        "petstore_auth": [
                            "create:order"
                        ]
                    }
                ]
            }
        },
        "/trading/order/deals": {
            "post": {
                "tags": [
                    "Trading"
                ],
                "summary": "Get order details.",
                "description": "Get order details",
                "operationId": "order.deals",
                "security": [
                    {
                        "petstore_auth": [
                            "create:order"
                        ]
                    }
                ]
            }
        },
        "/trading/order/book": {
            "post": {
                "tags": [
                    "Trading"
                ],
                "summary": "Get order book.",
                "description": "Get order book",
                "operationId": "order.book",
                "security": [
                    {
                        "petstore_auth": [
                            "create:order"
                        ]
                    }
                ]
            }
        },
        "/trading/order/pending": {
            "post": {
                "tags": [
                    "Trading"
                ],
                "summary": "Get order pending.",
                "description": "Get order pending",
                "operationId": "order.pending",
                "security": [
                    {
                        "petstore_auth": [
                            "create:order"
                        ]
                    }
                ]
            }
        },
        "/trading/order/pending_detail": {
            "post": {
                "tags": [
                    "Trading"
                ],
                "summary": "Get order pending detail.",
                "description": "Get order pending detail",
                "operationId": "order.pending_detail",
                "security": [
                    {
                        "petstore_auth": [
                            "create:order"
                        ]
                    }
                ]
            }
        },
        "/trading/order/finished": {
            "post": {
                "tags": [
                    "Trading"
                ],
                "summary": "Get order finished.",
                "description": "Get order finished",
                "operationId": "order.finished",
                "security": [
                    {
                        "petstore_auth": [
                            "create:order"
                        ]
                    }
                ]
            }
        },
        "/trading/order/finished_detail": {
            "post": {
                "tags": [
                    "Trading"
                ],
                "summary": "Get order finished_detail.",
                "description": "Get order finished_detail",
                "operationId": "order.finished_detail",
                "security": [
                    {
                        "petstore_auth": [
                            "create:order"
                        ]
                    }
                ]
            }
        },
        "/trading/order/market_last": {
            "post": {
                "tags": [
                    "Market"
                ],
                "summary": "Get order market_last.",
                "description": "Get order market_last",
                "operationId": "order.market_last",
                "security": [
                    {
                        "petstore_auth": [
                            "create:order"
                        ]
                    }
                ]
            }
        },
        "/trading/order/market_deals": {
            "post": {
                "tags": [
                    "Market"
                ],
                "summary": "Get order market_deals.",
                "description": "Get order market_deals",
                "operationId": "order.market_deals",
                "security": [
                    {
                        "petstore_auth": [
                            "create:order"
                        ]
                    }
                ]
            }
        }
    },
    "securityDefinitions": {
        "petstore_auth": {
            "type": "oauth2",
            "authorizationUrl": "http://api.bitex.com/api/auth/login",
            "flow": "implicit",
            "scopes": {
                "write:pets": "modify pets in your account",
                "read:pets": "read your pets"
            }
        },
        "api_key": {
            "type": "apiKey",
            "name": "api_key",
            "in": "header"
        }
    }
}
